[package]
name = "arm32"
version = "0.1.0"
edition = "2018"
description = "ARM32 kernel support"

[dependencies]
cfg-if = "1.0.0"
cortex-a = "6.1.0"
cortex-m = "0.7.3"
cortex-m-rt = "^0.6.15"
cortex-m-semihosting = "0.3.7"
cpu = { path = "../../drivers/cpu/" }
nmallocator = { path = "../../mm/nmallocator/" }
rpi = { path = "../../drivers/rpi/" }
stellarisd = { path = "../../drivers/firmware/arm/stellarisd/" }
wee_alloc = { version = "0.4.5", features = ["static_array_backend"] }

[features]
cortex_a = []
cortex_m = []
rpi2 = ["cortex_a", "rpi/rpi2"]
stellaris_6965 = ["cortex_m"]
stm32f407 = ["cortex_m"]
