[package]
name = "rpi"
version = "0.1.0"
edition = "2018"
description = "Drivers for RaspberryPi boards"

[dependencies]
cortex-a = "6.1.0"
device = { path = "../device" }
libbmu = { path = "../../lib/libbmu/" }
mailbox = { path = "../firmware/mailbox/" }
mio = { path = "../../mm/mio/" }
tock-registers = "0.7.0"

[features]
rpi3 = []
rpi2 = []
