[package]
name = "esp"
version = "0.1.0"
edition = "2018"
description = "Support for Xtensa Esp boards and RISCV in the fututre"

[target.'cfg(target_arch = "xtensa")'.dependencies]
esp32-hal = "0.3.0"

[dependencies]
device = { path = "../../device/" }

[features]
default = []
esp32 = []
