[package]
name = "stellarisd"
version = "0.1.0"
edition = "2018"
description = "Board support for Stellaris boards"

[dependencies]
cortex-m-semihosting = "0.3.7"
embedded-hal = "1.0.0-alpha.4"
libbmu = { path = "../../../../lib/libbmu/" }
novuskinc = { path = "../../../../include/novusk/" }
tm4c123x-hal = "0.10.2"
