[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 support for Novusk, mostly a kernel for the RaspberryPi"

[dependencies]
cortex-a = "6.1.0"
init = { path = "../../init/" }
mio = { path = "../../mm/mio/" }
kinfo = { path = "../../kernel/kinfo/" }
libbmu = { path = "../../lib/libbmu/" }
linked_list_allocator = "0.9.0"
modules = { path = "../../kernel/modules/" }
novuskinc = { path = "../../include/novusk/" }
r0 = "1.0.0"
rpi = { path = "../../drivers/rpi/" }
tock-registers = "0.7.0"

[features]
default = ["rpi3"]
rpi3 = ["rpi/rpi3"]
rpi4 = [] # soon
qemu_virt = []
